### ISSUE TITLE
exception when canceling save

### ISSUE THREAD

**Issue by hannesdelbeke** [bhowiebkr/python-node-editor#8]
if you open the example. and go to File>Save
and then cancel the filebrowser dialog.
you get the following exception
```
Traceback (most recent call last):
  File "C:\Users\hanne\OneDrive\Documents\repos\python-node-editor\main.py", line 91, in save_project
    self.node_widget.save_project(file_path)
  File "C:\Users\hanne\OneDrive\Documents\repos\python-node-editor\node_editor\gui\node_widget.py", line 121, in save_project
    nodes = item.nodes()
  File "C:\Users\hanne\OneDrive\Documents\repos\python-node-editor\node_editor\connection.py", line 37, in nodes
    return (self.start_pin.node(), self.end_pin.node())
TypeError: 'Button_Node' object is not callable
```

**Comment by bhowiebkr** [comment]
Sorry, I've been away for a while. I'll check this out and fix it. in time
